<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title-report')</title>
    <link rel="stylesheet" href="{{ public_path('css/page-layout.css') }}">
</head>

<body>

    <header>
        <label for="" class="form-code">BMA FORM</label>
        <div class="text-center">
            <img src="{{ public_path() . '/assets/image/report-header.png' }}" alt="page-header">
        </div>

    </header>

    <div class="page-content">
        @yield('content')
    </div>
    <div id="footer">
        <div class="page-number"></div>
    </div>
    {{-- <footer class="mt-5">
       
        <table class="table-content text-center">
            <tbody>
                <tr>
                    <td>
                        <small>
                            GENERATED DATE: @php
                                date_default_timezone_set('Asia/Manila');
                                echo date('m/d/Y h:m:s');
                            @endphp
                        </small>
                    </td>
                    <td><small>GENERATED BY: {{ strtoupper(Auth::user()->name) }}</small></td>

                </tr>
            </tbody>
        </table>
    </footer> --}}
</body>

</html>
