<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title-report')</title>
    <style>
         @page {
            margin: 100px 25px;
        }

        * {
            padding: 0;
            margin: 0;
            /* font-family: "Times New Roman", Times, serif */
        }

        header {
            position: fixed;
            top: 10px;
            left: 0px;
            right: 0px;
            text-align: left;
            justify-content: center;
        }

    </style>
</head>

<body>

    <header>
        <span class="form-code">BMA FORM @yield('form-code')<span>
                <center>
                    <img src="{{ public_path() . '/assets/image/report-header.png' }}" alt="page-header">
                </center>

    </header>
    @yield('content')
    <footer class="mt-5">
        <table class="table-content text-center">
            <tbody>
                <tr>
                    <td>
                        <small>
                            GENERATED DATE: @php
                                date_default_timezone_set('Asia/Manila');
                                echo date('m/d/Y h:m:s');
                            @endphp
                        </small>
                    </td>
                    <td><small>GENERATED BY: {{ strtoupper(Auth::user()->name) }}</small></td>

                </tr>
            </tbody>
        </table>
    </footer>
</body>

</html>
